---

- name: "Install 7-Zip from WinGet"
  ansible.windows.win_command: "winget install --id=7zip.7zip -e"

- name: Get HKCR:\*\shellex\ContextMenuHandlers\7-Zip\Default
  ansible.windows.win_reg_stat:
    path: HKCR:\*\shellex\ContextMenuHandlers\7-Zip
    name: ""
  register: regedit_7zip_default

- name: Set HKCR:\*\shellex\ContextMenuHandlers\7-Zip\Default
  ansible.windows.win_regedit:
    path: HKCR:\*\shellex\ContextMenuHandlers\7-Zip
    name: ""
    data: "-{{ regedit_7zip_default.value }}"
  when: regedit_7zip_default.value[0] != "-"