---

# https://www.tenforums.com/tutorials/80043-apply-local-group-policy-specific-user-windows-10-a.html
# https://docs.microsoft.com/en-us/windows/configuration/customize-windows-10-start-screens-by-using-group-policy
[]
