---

- name: Add Remmina APT repository
  ansible.builtin.apt_repository:
    repo: ppa:remmina-ppa-team/remmina-next
    state: present

- name: Install remmina
  apt:
    pkg:
      - remmina
      - remmina-plugin-rdp
      - remmina-plugin-secret
    state: present
