---

- name: "Install CPUID HWMonitor from WinGet"
  ansible.windows.win_command: "winget install --id=CPUID.HWMonitor -e"

- name: Remove C:\Users\Public\Desktop\CPUID HWMonitor.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\CPUID HWMonitor.lnk
    state: absent
