---

- name: "Install CPUID HWMonitor from WinGet"
  win_winget:
    name: 'CPUID.HWMonitor'

- name: Remove C:\Users\Public\Desktop\CPUID HWMonitor.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\CPUID HWMonitor.lnk
    state: absent
