---

- name: Install HWMonitor from Chocolatey
  win_chocolatey:
    name: hwmonitor
    state: latest

- name: Remove C:\Users\Public\Desktop\CPUID HWMonitor.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\CPUID HWMonitor.lnk
    state: absent
