---

# - name: Install Azure CLI from Chocolatey
#   win_chocolatey:
#     name: azure-cli
#     state: latest

- name: "Install Microsoft Azure CLI from WinGet"
  ansible.windows.win_command: "winget install --id=Microsoft.AzureCLI -e"
  # win_winget:
  #   name: Microsoft.AzureCLI
