---

- hosts: all
  roles:
    - bitwarden
    - dropbox
    - duplicati
    - firefox
    - spotify
    # - veracrypt # not installing
    - vlc
    - wireguard

- hosts: windows
  roles:
    - googlebackupandsync
