---

- hosts: spirou, spirou2
  roles:
    - geforcegamereadydriver
    - icue
    - samsungmagician

- import_playbook: chocolatey.yml
- import_playbook: common.yml
- import_playbook: development.yml
- import_playbook: video.yml

- hosts: desktops
  roles:
    - 7zip
    - discord
    - chrome
    - etcher
    - googlebackupandsync
    - hashtab # not trusted
    - imgburn # not trusted
    - libreoffice
    - malwarebytes
    - msteams
    - mullvad
    - paintnet
    - plex
    - pdfsam
    - steam
    - svtplaydl
    # - syncthing
    - teamviewer
    - tinymediamanager
    - treesize
