---

 - import_playbook: chocolatey.yml
 - import_playbook: common.yml
 - import_playbook: map_network_drives.yml

- hosts: desktop
  roles:
    # - asuspceac68 # not working
    - geforceexperience
    - icue
    # - ghub # not working
    - samsungmagician # not installing

    - bitwarden
    - chrome
    - discord
    - dropbox
    - duplicati
    - eadesktop
    - epicgameslauncher
    - googlebackupandsync
    - msteams
    - mullvad
    - paintnet # not installing
    - playnite
    - scummvm
    - slack
    - steam
    - plex
    - pdfsam
    - svtplaydl
    - tagspaces
    - tinymediamanager
    - wireguard

 - import_playbook: development.yml
 - import_playbook: utils.yml
 - import_playbook: video.yml
