---

- hosts: spirou
  roles:
    # - asuspceac68 # not working
    - geforceexperience
    # - geforcegamereadydriver
    - icue
    # - ghub # not working
    - samsungmagician

- import_playbook: chocolatey.yml
- import_playbook: common.yml
- import_playbook: map_network_drives.yml
- import_playbook: development.yml
- import_playbook: video.yml

- hosts: desktops
  roles:
    - 7zip
    - discord
    - chrome
    - cpuz
    - etcher
    - googlebackupandsync
    - gpuz
    - hashtab # not trusted
    - hdtune # not trusted
    - hwmonitor
    - imgburn # not trusted
    - libreoffice
    - malwarebytes
    - msteams
    # - mullvad # not working
    - paintnet
    - playnite
    - plex
    - pdfsam
    - recuva # not trusted
    - scummvm # not trusted
    - shellexview # not trusted
    - shellmenuview
    - slack
    - speedfan # not trusted
    - steam
    - svtplaydl
    - syncthing
    - tagspaces
    - teamviewer
    - testdiskphotorec
    - tinymediamanager
    - treesize
    - wifiinfoview
