---

- import_playbook: common.yml
#- import_playbook: map_network_drives.yml # only works once?

- hosts: desktop
  roles:
    - geforceexperience
    - icue
    # - ghub
    # - samsungmagician
    - bitwarden
    - chrome
    - discord # installation fails
    - dropbox
    - duplicacy
    - eadesktop # Installer hash does not match; to override this check use --force
    - epicgameslauncher # 2nd installation fails
    - googledrive
    - msteams
    - mullvad
    # - paintnet
    - playnite
    - scummvm
    - slack
    - steam
    - plex
    - pdfsam
    - svtplaydl
    # - tinymediamanager
    - wireguard
  ignore_errors: yes

- import_playbook: development.yml
- import_playbook: utils.yml
- import_playbook: video.yml
