---

 - import_playbook: chocolatey.yml
 - import_playbook: common.yml
 - import_playbook: map_network_drives.yml

- hosts: desktop
  roles:
    # - asuspceac68 # not working
    - geforceexperience
    # - geforcegamereadydriver
    - icue
    # - ghub # not working
    - samsungmagician # not installing

    - chrome
    - discord
    - msteams
    - mullvad # not working
    - paintnet # not installing
    # - playnite
    # - scummvm # not trusted
    # - slack
    - steam
    # - tagspaces
    - plex
    - svtplaydl
    - tinymediamanager
    - libreoffice
    # - pdfsam
    - eadesktop
    - epicgameslauncher

 - import_playbook: development.yml
 - import_playbook: utils.yml
 - import_playbook: video.yml
