---

- hosts: spirou
  roles:
    - geforcegamereadydriver
    - icue
    - ghub
    - samsungmagician

- import_playbook: chocolatey.yml
- import_playbook: common.yml
- import_playbook: map_network_drives.yml
- import_playbook: development.yml
- import_playbook: video.yml

- hosts: desktops
  roles:
    - 7zip
    - discord
    - chrome
    - cpuz
    - etcher
    - googlebackupandsync
    - gpuz
    - hashtab # not trusted
    - hdtune # not trusted
    - hwmonitor
    - imgburn # not trusted
    - libreoffice
    - malwarebytes
    - msteams
    - mullvad
    - paintnet
    - plex
    - pdfsam
    - speedfan # not trusted
    - steam
    - svtplaydl
    # - syncthing
    - teamviewer
    - tinymediamanager
    - treesize
