winget install --id 7zip.7zip -e
winget install --id Balena.Etcher -e
winget install --id Bitwarden.Bitwarden -e
winget install --id Discord.Discord -e
winget install --id Docker.DockerDesktop -e
winget install --id Git.Git -e
winget install --id Google.Chrome -e
winget install --id thehandbraketeam.handbrake -e
winget install --id Implbits.HashTab -e
winget install --id LibreOffice.LibreOffice -e
winget install --id Malwarebytes.Malwarebytes -e
winget install --id Microsoft.dotnet -e
winget install --id Microsoft.dotNetFramework -e
winget install --id Microsoft.Teams -e
winget install --id Microsoft.VisualStudio.Community
winget install --id Microsoft.VisualStudioCode -e
winget install --id Mozilla.Firefox -e
winget install --id MullvadVPN.MullvadVPN -e
winget install --id Nvidia.GeForceExperience -e
winget install --id OpenJS.Nodejs -e
winget install --id ScummVM.ScummVM -e
winget install --id SQLiteBrowser.SQLiteBrowser -e
winget install --id Spotify.Spotify -e
winget install --id TeamViewer.TeamViewer -e
winget install --id Valve.Steam -e
winget install --id VideoLAN.VLC -e