---

- name: "Install CPUID CPU-Z from WinGet"
  ansible.windows.win_command: "winget install --id=CPUID.CPU-Z -e"

- name: Remove C:\Users\Public\Desktop\CPUID CPU-Z.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\CPUID CPU-Z.lnk
    state: absent
