---

- name: Install CPU-Z from Chocolatey
  win_chocolatey:
    name: cpu-z
    state: latest

- name: Remove C:\Users\Public\Public Desktop\CPUID CPU-Z.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Public Desktop\CPUID CPU-Z.lnk
    state: absent
