---

- name: "Install CPUID CPU-Z from WinGet"
  win_winget:
    name: 'CPUID.CPU-Z'

- name: Remove C:\Users\Public\Desktop\CPUID CPU-Z.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\CPUID CPU-Z.lnk
    state: absent
