---

# - name: Install Google Backup and Sync from Chocolatey
#   win_chocolatey:
#     name: google-backup-and-sync
#     state: latest

- name: "Install Google Backup and Sync from WinGet"
  ansible.windows.win_command: "winget install --id=Google.BackupAndSync -e"

- name: Remove C:\Users\Public\Desktop\Google Docs.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\Google Docs.lnk
    state: absent

- name: Remove C:\Users\Public\Desktop\Google Sheets.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\Google Sheets.lnk
    state: absent

- name: Remove C:\Users\Public\Desktop\Google Slides.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\Google Slides.lnk
    state: absent

- name: Remove %USERPROFILE%\Desktop\Google Drive.lnk
  ansible.windows.win_file:
    path: "%USERPROFILE%\\Desktop\\Google Drive.lnk"
    state: absent
