---

# - name: Install Visual Studio Code Insiders .exe from code.visualstudio.com
#   ansible.windows.win_package:
#     path: https://code.visualstudio.com/sha/download?build=insider&os=win32-x64-user
#     state: present

- name: "Install Visual Studio Code Insiders from WinGet"
  ansible.windows.win_command: "winget install --id=Microsoft.VisualStudioCode.Insiders -e"
