---

# - name: Install SpeedFan from Chocolatey # not trusted
#   win_chocolatey:
#     name: speedfan
#     state: latest

- name: "Install Speedfan from WinGet"
  ansible.windows.win_command: "winget install --id=speed.fan -e"

- name: Remove %USERPROFILE%\Desktop\SpeedFan.lnk
  ansible.windows.win_file:
    path: "%USERPROFILE%\\Desktop\\SpeedFan.lnk"
    state: absent
