---

- name: "Install Speedfan from WinGet"
  win_winget:
    name: 'speed.fan'

- name: Remove %USERPROFILE%\Desktop\SpeedFan.lnk
  ansible.windows.win_file:
    path: "%USERPROFILE%\\Desktop\\SpeedFan.lnk"
    state: absent
