---

- name: "Install Visual Studio Community 2022 from WinGet"
  win_winget:
    name: 'Microsoft.VisualStudio.2022.Community'

- name: Set HKCR:\Directory\Background\shell\AnyCode
  ansible.windows.win_regedit:
    path: HKCR:\Directory\Background\shell\AnyCode
    name: LegacyDisable
    data: ""
    type: string

- name: Set HKCR:\Directory\shell\AnyCode
  ansible.windows.win_regedit:
    path: HKCR:\Directory\shell\AnyCode
    name: LegacyDisable
    data: ""
    type: string
