---

- name: "Install Steam from WinGet"
  win_winget:
    name: 'Valve.Steam'

- name: Remove C:\Users\Public\Desktop\Steam.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\Steam.lnk
    state: absent
