---

- name: "Install MediaInfo from WinGet"
  win_winget:
    name: 'MediaArea.MediaInfo-GUI'

- name: Remove %USERPROFILE%\Desktop\MakeMKV.lnk
  ansible.windows.win_file:
    path: "%USERPROFILE%\\Desktop\\MakeMKV.lnk"
    state: absent
