---

# - name: Install HandBrake from Chocolatey
#   win_chocolatey:
#     name: handbrake
#     state: latest

- name: "Install HandBrake from WinGet"
  ansible.windows.win_command: "winget install --id=HandBrake.HandBrake -e"

- name: Remove C:\Users\Public\Desktop\HandBrake.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\HandBrake.lnk
    state: absent
