---

- name: Install LibreOffice Calc from APT
  apt:
    name: libreoffice-calc
    state: latest
  become: yes

- name: Install LibreOffice Writer from APT
  apt:
    name: libreoffice-writer
    state: latest
  become: yes