---

- name: Install LibreOffice from Chocolatey
  win_chocolatey:
    name: libreoffice-fresh
    state: latest

- name: Remove C:\Users\Public\Public Desktop\LibreOffice 7.1.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Public Desktop\LibreOffice 7.1.lnk
    state: absent
