---

- name: "Install LibreOffice from WinGet"
  win_winget:
    name: TheDocumentFoundation.LibreOffice

- name: Remove C:\Users\Public\Desktop\LibreOffice 7.1.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\LibreOffice 7.1.lnk
    state: absent
