---

- name: "Install LibreOffice from WinGet"
  ansible.windows.win_command: "winget install --id=LibreOffice.LibreOffice -e"

- name: Remove C:\Users\Public\Desktop\LibreOffice 7.1.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\LibreOffice 7.1.lnk
    state: absent
