---

- name: Install GeForce Experience from Chocolatey
  win_chocolatey:
    name: geforce-experience
    state: latest

- name: Remove C:\Users\Public\Public Desktop\GeForce Experience.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Public Desktop\GeForce Experience.lnk
    state: absent
