---

- name: "Install Nvidia GeForce Experience from WinGet"
  win_winget:
    name: 'Nvidia.GeForceExperience'

- name: Remove C:\Users\Public\Desktop\GeForce Experience.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\GeForce Experience.lnk
    state: absent
