---

- name: "Install Nvidia GeForce Experience from WinGet"
  ansible.windows.win_command: "winget install --id=Nvidia.GeForceExperience -e"

- name: Remove C:\Users\Public\Desktop\GeForce Experience.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\GeForce Experience.lnk
    state: absent
