---

- name: Install Spotify from Chocolatey
  win_chocolatey:
    name: spotify
    state: latest

- name: Remove %USERPROFILE&\Desktop\Spotify.lnk
  ansible.windows.win_file:
    path: "%USERPROFILE%\\Desktop\\Spotify.lnk"
    state: absent
