---

- name: "Install Spotify from WinGet"
  ansible.windows.win_command: "winget install --id=Spotify.Spotify -e"

- name: Remove %USERPROFILE%\Desktop\Spotify.lnk
  ansible.windows.win_file:
    path: "%USERPROFILE%\\Desktop\\Spotify.lnk"
    state: absent
