---

- name: "Install Spotify from WinGet"
  win_winget:
    name: Spotify.Spotify
    runas: Viktor
  # ansible.windows.win_shell: "$id = 'Spotify.Spotify'; If (((winget list --id \"$id\" -e --source winget) -join ';') -notlike \"*$id*\") { winget install --id \"$id\" -e -h --accept-package-agreements --accept-source-agreements }"

- name: Remove %USERPROFILE%\Desktop\Spotify.lnk
  ansible.windows.win_file:
    path: "%USERPROFILE%\\Desktop\\Spotify.lnk"
    state: absent
