---

- name: "Install TechPowerUp GPU-Z from WinGet"
  ansible.windows.win_command: "winget install --id=TechPowerUp.GPU-Z -e"

- name: Remove C:\Users\Public\Desktop\GPU-Z.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\GPU-Z.lnk
    state: absent
