---

- name: Install Git from APT
  apt:
    name: git
    state: latest
  become: yes

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: .gitconfig
    dest: ~/.gitconfig
    owner: viktor
    group: viktor
    mode: '0600'