---

- name: "Install Git from WinGet"
  win_winget:
    name: 'Git.Git'
  # /NoShellIntegration /NoGuiHereIntegration /NoShellHereIntegration

- name: Set HKCR:\Directory\Background\shell\git_gui
  ansible.windows.win_regedit:
    path: HKCR:\Directory\Background\shell\git_gui
    name: LegacyDisable
    data: ""
    type: string

- name: Set HKCR:\Directory\Background\shell\git_shell
  ansible.windows.win_regedit:
    path: HKCR:\Directory\Background\shell\git_shell
    name: LegacyDisable
    data: ""
    type: string

- name: Set HKCR:\Directory\shell\git_gui
  ansible.windows.win_regedit:
    path: HKCR:\Directory\shell\git_gui
    name: LegacyDisable
    data: ""
    type: string

- name: Set HKCR:\Directory\shell\git_shell
  ansible.windows.win_regedit:
    path: HKCR:\Directory\shell\git_shell
    name: LegacyDisable
    data: ""
    type: string

# Remember SSH passphrase: https://gist.github.com/danieldogeanu/16c61e9b80345c5837b9e5045a701c99
