---

- name: Install Chocolatey packages
  win_chocolatey:
    name: "{{ chocolatey_packages }}"
  tags: chocolatey_packages:install

#- name: Upgrade Chocolatey packages
#  win_chocolatey:
#    name: all
#    state: latest
#  tags: chocolatey_packages:upgrade