---

- name: Install Chrome from Chocolatey
  win_chocolatey:
    name: googlechrome
    state: latest

- name: Remove C:\Users\Public\Desktop\Google Chrome.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\Google Chrome.lnk
    state: absent
