---

- name: "Install Google Chrome from WinGet"
  win_winget:
    name: 'Google.Chrome'

- name: Remove C:\Users\Public\Desktop\Google Chrome.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\Google Chrome.lnk
    state: absent
