---

- name: "Install Google Chrome from WinGet"
  ansible.windows.win_command: "winget install --id=Google.Chrome -e"

- name: Remove C:\Users\Public\Desktop\Google Chrome.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\Google Chrome.lnk
    state: absent
