---

# - name: Install Duplicati from Chocolatey
#   win_chocolatey:
#     name: duplicati # not trusted
#     state: latest

- name: "Install Duplicati 2 from WinGet"
  ansible.windows.win_command: "winget install --id=Duplicati.Duplicati -e"

- name: Remove C:\Users\Public\Desktop\Duplicati 2.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\Duplicati 2.lnk
    state: absent
