---

- name: Install Malwarebytes from Chocolatey
  win_chocolatey:
    name: malwarebytes
    state: latest

- name: "Install Malwarebytes from WinGet"
  ansible.windows.win_command: "winget install --id=Malwarebytes.Malwarebytes -e"

- name: Remove C:\Users\Public\Desktop\Malwarebytes.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\Malwarebytes.lnk
    state: absent
