---

- name: Install Malwarebytes from Chocolatey
  win_chocolatey:
    name: malwarebytes
    state: latest

- name: Remove C:\Users\Public\Public Desktop\Malwarebytes.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Public Desktop\Malwarebytes.lnk
    state: absent
