---

- name: "Install Malwarebytes from WinGet"
  win_winget:
    name: 'Malwarebytes.Malwarebytes'

- name: Remove C:\Users\Public\Desktop\Malwarebytes.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\Malwarebytes.lnk
    state: absent
