---

- name: Install Discord from Chocolatey
  win_chocolatey:
    name: discord
    state: latest

- name: Remove %USERPROFILE%\Desktop\Discord.lnk
  ansible.windows.win_file:
    path: "%USERPROFILE%\\Desktop\\Discord.lnk"
    state: absent
