---

- name: "Install Discord from WinGet"
  win_winget:
    name: 'Discord.Discord'

- name: Remove %USERPROFILE%\Desktop\Discord.lnk
  ansible.windows.win_file:
    path: "%USERPROFILE%\\Desktop\\Discord.lnk"
    state: absent
