---

- name: "Install Discord from WinGet"
  ansible.windows.win_command: "winget install --id=Discord.Discord -e"

- name: Remove %USERPROFILE%\Desktop\Discord.lnk
  ansible.windows.win_file:
    path: "%USERPROFILE%\\Desktop\\Discord.lnk"
    state: absent
