---

- name: "Install TreeSize Free from WinGet"
  ansible.windows.win_command: "winget install --id=JAMSoftware.TreeSizeFree -e"

- name: Set HKCR:\Directory\Background\shell\TreeSize Free
  ansible.windows.win_regedit:
    path: HKCR:\Directory\Background\shell\TreeSize Free
    name: LegacyDisable
    data: ""
    type: string

- name: Set HKCR:\Folder\shell\TreeSize Free
  ansible.windows.win_regedit:
    path: HKCR:\Folder\shell\TreeSize Free
    name: LegacyDisable
    data: ""
    type: string
