---

- name: "Install Dropbox from WinGet"
  win_winget:
    name: 'Dropbox.Dropbox'

- name: Remove %USERPROFILE%\Desktop\Dropbox.lnk
  ansible.windows.win_file:
    path: "%USERPROFILE%\\Desktop\\Dropbox.lnk"
    state: absent
