---

- name: "Install Dropbox from WinGet"
  ansible.windows.win_command: "winget install --id=Dropbox.Dropbox -e"

- name: Remove %USERPROFILE%\Desktop\Dropbox.lnk
  ansible.windows.win_file:
    path: "%USERPROFILE%\\Desktop\\Dropbox.lnk"
    state: absent
