---

- name: "Install MakeMKV from WinGet"
  win_winget:
    name: 'GuinpinSoft.MakeMKV'

- name: Remove %USERPROFILE%\Desktop\MakeMKV.lnk
  ansible.windows.win_file:
    path: "%USERPROFILE%\\Desktop\\MakeMKV.lnk"
    state: absent

# Key: https://www.makemkv.com/forum/viewtopic.php?t=1053
