---

- name: Install Microsoft Teams from Chocolatey
  win_chocolatey:
    name: microsoft-teams
    state: latest

- name: Remove %USERPROFILE&\Desktop\Microsoft Teams.lnk
  ansible.windows.win_file:
    path: "%USERPROFILE%\\Desktop\\Microsoft Teams.lnk"
    state: absent
