---

- name: "Install Microsoft Teams from WinGet"
  win_winget:
    name: 'Microsoft.Teams'

- name: Remove %USERPROFILE%\Desktop\Microsoft Teams.lnk
  ansible.windows.win_file:
    path: "%USERPROFILE%\\Desktop\\Microsoft Teams.lnk"
    state: absent
