---

- name: Install .NET SDK for Windows
  when: ansible_os_family == "Windows"
  include_tasks: windows.yml
  
- name: Install .NET SDK for Ubuntu
  when: ansible_distribution == "Ubuntu"
  include_tasks: ubuntu.yml
