---

# https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2104-

- name: Install Microsoft package signing key .deb package
  apt:
    deb: https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb
    state: present

- name: Install apt-transport-https from APT
  apt:
    name: apt-transport-https
    state: latest
    update_cache: yes

- name: Install .NET SDK 5.0 from APT
  apt:
    name: dotnet-sdk-5.0
    state: latest
    update_cache: yes
