---

- name: Install Playnite from Chocolatey
  win_chocolatey:
    name: playnite
    state: latest

- name: Remove %USERPROFILE%\Desktop\Playnite.lnk
  ansible.windows.win_file:
    path: "%USERPROFILE%\\Desktop\\Playnite.lnk"
    state: absent
