---

- name: "Install Playnite from WinGet"
  win_winget:
    name: 'Playnite.Playnite'

- name: Remove %USERPROFILE%\Desktop\Playnite.lnk
  ansible.windows.win_file:
    path: "%USERPROFILE%\\Desktop\\Playnite.lnk"
    state: absent
