---

- name: "Install Playnite from WinGet"
  ansible.windows.win_command: "winget install --id=Playnite.Playnite -e"

- name: Remove %USERPROFILE%\Desktop\Playnite.lnk
  ansible.windows.win_file:
    path: "%USERPROFILE%\\Desktop\\Playnite.lnk"
    state: absent
