---

- name: Install Logitech G HUB .exe from download01.logi.com
  ansible.windows.win_package:
    path: https://download01.logi.com/web/ftp/pub/techsupport/gaming/lghub_installer.exe
    product_id: "{521c89be-637f-4274-a840-baaf7460c2b2}"
    state: present

- name: Remove C:\Users\Public\Desktop\Logitech G HUB.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\Logitech G HUB.lnk
    state: absent
