---

- name: "Install Docker Desktop from WinGet"
  ansible.windows.win_command: "winget install --id=Docker.DockerDesktop -e"

- name: Remove %USERPROFILE%\Desktop\Docker Desktop.lnk
  ansible.windows.win_file:
    path: "%USERPROFILE%\\Desktop\\Docker Desktop.lnk"
    state: absent
