---

- name: "Install Docker Desktop from WinGet"
  win_winget:
    name: 'Docker.DockerDesktop'

- name: Remove %USERPROFILE%\Desktop\Docker Desktop.lnk
  ansible.windows.win_file:
    path: "%USERPROFILE%\\Desktop\\Docker Desktop.lnk"
    state: absent
