---

- name: Install Docker Desktop from Chocolatey
  win_chocolatey:
    name: docker-desktop
    state: latest

- name: Remove %USERPROFILE%\Desktop\Docker Desktop.lnk
  ansible.windows.win_file:
    path: "%USERPROFILE%\\Desktop\\Docker Desktop.lnk"
    state: absent
