---

- name: "Install ScummVM from WinGet"
  ansible.windows.win_command: "winget install --id=ScummVM.ScummVM -e"

- name: Remove %USERPROFILE%\Desktop\ScummVM.lnk
  ansible.windows.win_file:
    path: "%USERPROFILE%\\Desktop\\ScummVM.lnk"
    state: absent
