---

- name: "Install ScummVM from WinGet"
  win_winget:
    name: 'ScummVM.ScummVM'

- name: Remove %USERPROFILE%\Desktop\ScummVM.lnk
  ansible.windows.win_file:
    path: "%USERPROFILE%\\Desktop\\ScummVM.lnk"
    state: absent
