---

- name: "Install Bitwarden from WinGet"
  ansible.windows.win_command: "winget install --id=Bitwarden.Bitwarden -e"

- name: Install Bitwarden CLI from Chocolatey
  win_chocolatey:
    name: bitwarden-cli
    state: latest

- name: Remove C:\Users\Public\Desktop\Bitwarden.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\Bitwarden.lnk
    state: absent
