---

- name: Install Bitwarden from Chocolatey
  win_chocolatey:
    name: bitwarden
    state: latest

- name: Install Bitwarden CLI from Chocolatey
  win_chocolatey:
    name: bitwarden-cli
    state: latest

- name: Remove C:\Users\Public\Public Desktop\Bitwarden.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Public Desktop\Bitwarden.lnk
    state: absent
