---

- name: "Install Bitwarden from WinGet"
  win_winget:
    name: 'Bitwarden.Bitwarden'

- name: Remove C:\Users\Public\Desktop\Bitwarden.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\Bitwarden.lnk
    state: absent
