---

- name: Install Bitwarden from Chocolatey
  win_chocolatey:
    name: bitwarden
    state: latest

- name: Install Bitwarden CLI from Chocolatey
  win_chocolatey:
    name: bitwarden-cli
    state: latest
