---

- name: Install PDFsam from Chocolatey
  win_chocolatey:
    name: pdfsam
    state: latest

- name: Remove C:\Users\Public\Public Desktop\PDFsam Basic.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Public Desktop\PDFsam Basic.lnk
    state: absent
