---

- name: "Install PDFsam Basic from WinGet"
  ansible.windows.win_command: "winget install --id=PDFsam.PDFsam -e"

- name: Remove C:\Users\Public\Desktop\PDFsam Basic.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\PDFsam Basic.lnk
    state: absent
