---

- name: "Install PDFsam Basic from WinGet"
  win_winget:
    name: 'PDFsam.PDFsam'

- name: Remove C:\Users\Public\Desktop\PDFsam Basic.lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\PDFsam Basic.lnk
    state: absent
