---

# - name: Install DB Browser for SQLite from Chocolatey
#   win_chocolatey:
#     name: sqlitebrowser
#     state: latest

- name: "Install DB Browser for SQLite from WinGet"
  ansible.windows.win_command: "winget install --id=DBBrowserForSQLite.DBBrowserForSQLite -e"

- name: Remove C:\Users\Public\Desktop\DB Browser (SQLCipher).lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\DB Browser (SQLCipher).lnk
    state: absent

- name: Remove C:\Users\Public\Desktop\DB Browser (SQLite).lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\DB Browser (SQLite).lnk
    state: absent
