---

- name: "Install DB Browser for SQLite from WinGet"
  win_winget:
    name: 'DBBrowserForSQLite.DBBrowserForSQLite'

- name: Remove C:\Users\Public\Desktop\DB Browser (SQLCipher).lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\DB Browser (SQLCipher).lnk
    state: absent

- name: Remove C:\Users\Public\Desktop\DB Browser (SQLite).lnk
  ansible.windows.win_file:
    path: C:\Users\Public\Desktop\DB Browser (SQLite).lnk
    state: absent
